### ISSUE TITLE
Return statement in anonymous function surrounded by if else block

### ISSUE THREAD

**Issue by dscholven** [djoos/Symfony-coding-standard#104]
```
if ($condition) {
    $this->closure = function ($var) {
        return $var*2;
    };
    ....
} else {
    ....
}
```

leads to "Do not use else, elseif, break after if and case conditions which return or throw something"

**Comment by wickedOne** [comment]
yup, closures are my nemesis B| just ran into another one which triggers the
> Use return null; when a function explicitly returns null values and use return; when the function returns void values.

error while it shouldn't... will see whether i can find some time to fix those...

**Comment by ZhukV** [comment]
Clone is #119  and #105

**Comment by istrof** [comment]
Clone of #118
