### ISSUE TITLE
License agreement

### ISSUE THREAD

**Issue by Matan** [djoos/Symfony-coding-standard#110]
Hi!

What is the license agreement for the use of this repo?

Thanks!

**Comment by djoos** [comment]
Good question!

Answer: MIT; I'll made a note to add the missing LICENSE file to the repo...

HTH!

**Comment by djoos** [comment]
FYI: [LICENSE](https://github.com/djoos/Symfony-coding-standard/blob/master/LICENSE)

Have a great day!
David
