### ISSUE TITLE
Opening brace should not match one-lined anonymous function

### ISSUE THREAD

**Issue by Soullivaneuh** [djoos/Symfony-coding-standard#122]
Found on Symfony codebase: https://github.com/symfony/symfony/blob/cf898572a0194340ca2d8111891f8a6b9f860654/src/Symfony/Component/Config/Definition/Builder/ExprBuilder.php#L40

But phpcs will say:

```
Opening brace must be the last content on the line
Closing brace must be on a line by itself
Missing blank line before return statement
```

See also: https://github.com/squizlabs/PHP_CodeSniffer/issues/1580

Workaround:

```xml
<exclude name="Squiz.Functions.MultiLineFunctionDeclaration.ContentAfterBrace"/>
<exclude name="Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore"/>
<exclude name="PEAR.WhiteSpace.ScopeClosingBrace.Line"/>
<exclude name="Symfony.Formatting.BlankLineBeforeReturn.Invalid"/>
```

**Comment by Soullivaneuh** [comment]
> don't think that pointing to a piece of code in the symfony repo

Maybe some Symfony maintainer could answer, but I don't think why they will not apply Symfony coding standard on the Symfony codebase. :-)

**Comment by djoos** [comment]
Hi guys,

the [coding standards](https://symfony.com/doc/current/contributing/code/standards.html) page is what we base us on as codebases (even the Symfony repo!) could have bits (for different, sensible reasons) of legacy code that is not in-line with the standard... Those are then up to the CI setup on the codebase to be knowingly excluded.

Hope this helps!
