### ISSUE TITLE
Symfony.Commenting.FunctionComment.MissingParamTag should not complain if no params are documented and they are all typehinted

### ISSUE THREAD

**Issue by stof** [djoos/Symfony-coding-standard#124]
If all arguments of the method are typehinted, duplicating the info in the phpdoc does not make sense.
currently, the sniff requires either adding all `@param` or removing the phpdoc entirely. But this second option forces to remove the description too.

**Comment by wickedOne** [comment]
wouldn't this "break" ide info bubbles and phpdocumentor (i.e. not being completely useless)?

**Comment by stof** [comment]
IDEs are able to read PHP typehints since years (they are even able to generate this phpdoc for you when you have a requirement to keep it).

and phpdocumentor also supports using the native typehints AFAIK.

**Comment by djoos** [comment]
FYI: closing this one off - let's continue this issue in #120.
