### ISSUE TITLE
PHP Fatal Error: Interface 'PHP_CodeSniffer\Sniffs\Sniff' not found

### ISSUE THREAD

**Issue by frankgraave** [djoos/Symfony-coding-standard#133]
Hi there,

I've searched the open and closed issues here, but did not found any solution to my problem.

I'm trying to get some Symfony coding standards in my project (in PhpStorm) with codesniffer. Unfortunately I'm getting this error when working on a file:

```
PHP Code Sniffer
phpcs: PHP Fatal error:  Interface 'PHP_CodeSniffer\Sniffs\Sniff' not found in /Users/frankgraave/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Symfony/Sniffs/Arrays/MultiLineArrayCommaSniff.php on line 32
```

```
Fatal error: Interface 'PHP_CodeSniffer\Sniffs\Sniff' not found in /Users/frankgraave/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Symfony/Sniffs/Arrays/MultiLineArrayCommaSniff.php on line 32
```

I've tried it with CodeSniffer 2.7.0 and 2.9.1 but no succes. Any help would be great!

**Comment by xalopp** [comment]
@frankgraave you must use PHP CodeSniffer 3.0 or later in order the use the latest version this coding standard!

**Comment by djoos** [comment]
@xalopp is spot on: since v2.11.0 of this project PHP CodeSniffer 3.0 or later is required.

Please give a shout if you have any further issues - in the meantime I'll close this issue!
