### ISSUE TITLE
vendor/bin/phpcs not available

### ISSUE THREAD

**Issue by dan-nl** [djoos/Symfony-coding-standard#142]
when i require this component in a project using `composer require --dev escapestudios/symfony2-coding-standard:3.x-dev`, `vendor/bin/phpcs` is not available. when i add php codesniffer as a dev dependency in my own project, `composer require --dev squizlabs/php_codesniffer:3.*`,`vendor/bin/phpcs` becomes available.

it appears that the move of `squizlabs/php_codesniffer` from `require` to `require-dev` may be causing of the issue or i’m installing this component incorrectly.

**Comment by djoos** [comment]
Hi @dan-nl,

thanks for reaching out!

This sounds like #136... I haven't heard back on my suggestion there - any chance you could give that a go and feed back?

Thanks in advance!
David

**Comment by dan-nl** [comment]
here's an example repo that demonstrates the issue: https://github.com/dan-nl/phpcs-example
