### ISSUE TITLE
Bug with AssignmentSpacing and =&

### ISSUE THREAD

**Issue by carusogabriel** [djoos/Symfony-coding-standard#166]
When using the Sniff `Symfony.Whitespace.AssignmentSpacing` and the operator `=&`, I get an error, but the code is like:

```php
$this->foo[$bar] =& $baz['quox'];
```

**Comment by carusogabriel** [comment]
My bad, I was confusing this with `+=`, `*=`, `.=` :man_facepalming:

**Comment by djoos** [comment]
No problem, thanks @carusogabriel!
