### ISSUE TITLE
phpcs:ignore breaks MultiLineArrayComma if used on last element

### ISSUE THREAD

**Issue by blastoise365** [djoos/Symfony-coding-standard#175]
Initially, I've posted this issue to squizlabs, but it seems that it's related to this repo. (https://github.com/squizlabs/PHP_CodeSniffer/issues/2672)

This code will work fine:

```
$array = [
    'aaaaa',
    'bbbbb',
];
```

But this one will report MultiLineArrayComma problem

```
$array = [
    'aaaaa',
    'bbbbb', // phpcs:ignore
];
```

My example why I'm using ignore on last element: (I'm getting some results with guzzle and keys in response are not properly named so I'm ignoring camel case on those)

```
$bot->userStorage()->save([
    'x_task_option_'.$i.'_id' => $taskData->Results[$i]->id, // phpcs:ignore Zend.NamingConventions.ValidVariableName.NotCamelCaps
    'x_task_option_'.$i.'_name' => $taskData->Results[$i]->name, // phpcs:ignore Zend.NamingConventions.ValidVariableName.NotCamelCaps
]);
```

**Comment by xalopp** [comment]
@blastoise365 I have created a PR #177. Would be great if you can confirm if it's fix the issue.

**Comment by blastoise365** [comment]
@xalopp I can confirm that this is fixing the issue.
