### ISSUE TITLE
Symfony.ControlStructure.UnaryOperators.Invalid fails on ++self::$x

### ISSUE THREAD

**Issue by SimonHeimberg** [djoos/Symfony-coding-standard#179]
In case of class constants, postfix is forced (`self::$x++` is valid, `++self::$x` is invalid).
Is this expected?

Missing test cases in [Symfony/Tests/ControlStructure/UnaryOperatorsUnitTest.inc](
https://github.com/djoos/Symfony-coding-standard/blob/47f8f07/Symfony/Tests/ControlStructure/UnaryOperatorsUnitTest.inc):
```php
++Class::$v; // should be valid, but fails currently
Class::$v++; // valid
++$obj->v; // valid
$obj->v++;  // valid
```
---

version: 3.10.0 (of escapestudios/symfony2-coding-standard)

**Comment by mmoll** [comment]
@SimonHeimberg Could you check GH-181?
