### ISSUE TITLE
[Current Sniffs] Structure

### ISSUE THREAD

**Issue by wickedOne** [djoos/Symfony-coding-standard#66]
this issue lists all sniffs currently implemented in this repository as described in the [structure segment](http://symfony.com/doc/current/contributing/code/standards.html#structure) of the symfony coding standard.

this issue can be marked as resolved once the example class at the bottom triggers all mentioned errors when checked with this standard (be sure to remove all comment lines before checking).

at this time i'm not entirely sure how to check for ``Use return null; when a function explicitly returns null values and use return; when the function returns void values`` so any suggestions on that are welcome.

### Structure
- [x] Add a single space after each comma delimiter.
- [x] Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator.
- [x] Place unary operators (!, --, ...) adjacent to the affected variable.
- [x] Always use identical comparison unless you need type juggling.
- [x] Use Yoda conditions when checking a variable against an expression to avoid an accidental assignment inside the condition statement (this applies to ==, !=, ===, and !==).
- [x] Add a comma after each array item in a multi-line array, even after the last one.
- [x] Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement).
- [x] Use return null; when a function explicitly returns null values and use return; when the function returns void values.
- [x] Use braces to indicate control structure body regardless of the number of statements it contains.
- [x] Define one class per file - this does not apply to private helper classes that are not intended to be instantiated from the outside and thus are not concerned by the PSR-0 and PSR-4 autoload standards.
- [x] Declare the class inheritance and all the implemented interfaces on the same line as the class name.
- [x] Declare class properties before methods.
- [x] Declare public methods first, then protected ones and finally private ones. The exceptions to this rule are the class constructor and the setUp() and tearDown() methods of PHPUnit tests, which must always be the first methods to increase readability.
- [x] Declare all the arguments on the same line as the method/function name, no matter how many arguments there are.
- [x] Use parentheses when instantiating classes regardless of the number of arguments the constructor has.
- [x] Exception and error message strings must be concatenated using sprintf.
- [x] Calls to trigger_error with type E_USER_DEPRECATED must be switched to opt-in via @ operator. 
- [x] Do not use else, elseif, break after if and case conditions which return or throw something.
- [x] Do not use spaces around [ offset accessor and before ] offset accessor.

```php
<?php

namespace Symfony2;

// Declare the class inheritance and all the implemented interfaces on the same line as the class name
class Foo
    extends Bar
    implements Baz
{
    // Add a comma after each array item in a multi-line array, even after the last one
    private $a = [
        'foo',
        'bar'
    ];

    // Add a single space after each comma delimiter
    public function __construct($a,$b)
    {
        // Always use identical comparison unless you need type juggling
        if ($a == $b) {
            // Place unary operators (!, --, ...) adjacent to the affected variable
            $a = $b++;
        }
    }

    // Declare class properties before methods;
    private $b;

    // Declare public methods first, then protected ones and finally private ones.
    protected function bar()
    {
        // Use parentheses when instantiating classes regardless of the number of arguments the constructor has
        $foo = new Bar;

        // Do not use spaces around [ offset accessor and before ] offset accessor.
        $this->a [ 'foo' ] = $foo;
    }

    // Declare all the arguments on the same line as the method/function name, no matter how many arguments there are
    public function baz(
        $foo,
        $bar
    ){
        // Use Yoda conditions when checking a variable against an expression
        if ($foo === 1) {
            // Exception and error message strings must be concatenated using sprintf
            throw new \Exception('Bar'.$foo);
        // Do not use else, elseif, break after if and case conditions which return or throw something
        } else {
            // Add a single space around binary operators (==, &&, ...)
            if ($foo===$bar) {
                // Calls to trigger_error with type E_USER_DEPRECATED must be switched to opt-in via @ operator.
                trigger_error('deprecation', E_USER_DEPRECATED);
            }
        }
    }

    public function foo($a, $b)
    {
        // Use braces to indicate control structure body regardless of the number of statements it contains;
        if ($a === $b)
            ++$a;
            // Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement);
            return $b;    
    }
}

// Define one class per file
class Bar
{

}

```

**Comment by wickedOne** [comment]
this one is nearly done when the remaining pull requests are merged.
there's still one i'm struggling with:
> Use return null; when a function explicitly returns null values and use return; when the function returns void values.

even though i *think* i know what it means (a function which returns a variety of values should return null, otherwise void) i'm not 100% sure about that. and thinking of it: why should a function return void to begin with?

@djoos @stof any suggestions?

**Comment by djoos** [comment]
> even though i think i know what it means (a function which returns a variety of values should return null, otherwise void) i'm not 100% sure about that.

+1 @wickedOne, that's also my understanding!

**Comment by stof** [comment]
@wickedOne A function returning void is a function will never returns a useful value (PHP 7.1 has an explicit return type `void`).
In a void returning function, you either have `return;` or no return at all in the code path. `return something` is forbidden (at compile time) for any `something` (static value, other method call, etc...)

**Comment by wickedOne** [comment]
thanks @djoos & @stof for the input! 

@stof:
>  function returning void is a function will never returns a useful value.

so the sniff has to raise an error at the following
```php
public function foo(): void
{
    return null;
}
```
and has to be fine with
```php
public function foo(): void
{
    return;
}
```
and simply can ignore the return statements pre-php 7.1 or functions without an explicit ``void`` return type defined?

**Comment by stof** [comment]
@wickedOne yes indeed. these are the invalid and valid samples (and actually, the would be compile-time errors from PHP)

**Comment by wickedOne** [comment]
thanks @stof than [this one](https://github.com/djoos/Symfony-coding-standard/pull/91) should sniff that

**Comment by wickedOne** [comment]
this one is done as well...
