### ISSUE TITLE
PHP7 Group use statement issue

### ISSUE THREAD

**Issue by chosroes** [djoos/Symfony-coding-standard#95]
If I use group use statement allowed by PHP7, I get :
phpcs: There must be one USE keyword per declaration

**Comment by wickedOne** [comment]
using a coding standard isn't about what's allowed by php (which is a lot).
it's about what set of rules you (and your team) decide to follow as the "standard" to create consistency in your codebase.

> Remember that the main advantage of standards is that every piece of code looks and feels familiar, it's not about this or that being more readable.
https://symfony.com/doc/current/contributing/code/standards.html

you might want to read the entire page as it highlights all of the rules and for some gives an explanation of why those rules are enforced.

also remember: if you, for some reason, want to ignore one or more rules enforced by this standard, simply modify your local copy of the [ruleset.xml](https://github.com/djoos/Symfony-coding-standard/blob/master/Symfony/ruleset.xml) by setting the error's severity to ``0``
